config/routes.rb
Rails.application.routes.draw do

  get 'notification/index'
  get 'relationships/create'
  get 'relationships/destroy'
  get 'topics/my_topic' => 'topics#my_topic'
  resources :users, only: [:index]
  resources :relationships, only:[:create, :destroy]
  resources :conversations do
    resources :messages
  end

  devise_for :users, controllers:{
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :topics do
    resources :comments
    resources :likes, only:[:create, :destroy]

    collection do
      post :confirmed
    end
  end

  root 'topics#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine,at: "/letter_opener"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many :notifications, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comments_params)
    @topic = @comment.topic
    @notification = @comment.notifications.build(user_id: @topic.user.id)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to topic_path(@topic), notice: 'コメントを投稿しました' }
        format.js {render :index}
        unless @comment.topic.user_id == current_user.id
          Pusher.trigger("user_#{@comment.topic.user_id}_channel","comment_created",{
            message: "あなたの作成した投稿にコメントがつきました"
            })
          end
          Pusher.trigger("user_#{@comment.topic.user_id}_channel","notification_created",{
            unread_counts: Notification.where(user_id: @comment.topic.user.id, read: false).count
            })
          else
            format.html { render :new }
          end
        end
      end

      def edit
        @comment = Comment.find(params[:id])
        respond_to do |format|
          format.js {render :edit}
        end
      end

      def update
        @comment = Comment.find(params[:id])
        @topic = @comment.topic
        @comments = @topic.comments.order(created_at: :desc)
        respond_to do |format|
          if @comment.update(comments_params)
            format.html { redirect_to topic_path(@topic), notice: 'コメントを更新しました' }
            format.js {render :update}
          else
            format.js {render :new}
          end
        end
      end


      def destroy
        @comment = Comment.find(params[:id])
        respond_to do |format|
          if @comment.destroy
            format.html { redirect_to topic_path(@topic), notice: 'コメントを削除しました' }
            format.js {render :index}
          else
            format.html { render :new }
          end
        end
      end

      private
      def comments_params
        params.require(:comment).permit(:topic_id, :content)
      end
    end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_edit.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <li>
        <% if comment.id.to_s == params[:id] %>
        <%= form_for([topic,comment] ,remote: true) do |f| %>
          <%= f.hidden_field :topic_id %>
          <div class="field">
            <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
          </div>
          <div class="actions">
            <%= f.submit  "コメントを更新する" ,class:"btn btn-primary"%>
          </div>
          <% end %>
          <% else %>
          <p class="left"><%= comment.user.name %>さんがコメントしました。</p>
          <p class="left"><%= comment.content %></p>
          <% end %>
        </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/_form.html.erb
<%= form_for([topic,comment], remote: true) do |f| %>
  <%= f.hidden_field :topic_id %>
  <div class="field">
    <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit "コメントする" ,class:"btn btn-primary"%>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <li>
        <p class="left"><%= comment.user.name %>さんがコメントしました。</p>
        <p class="left"><%= comment.content %></p>
        <% if current_user.id == comment.user.id %>
          <p class="right">
            <%= link_to '', edit_topic_comment_path(topic, comment), class: "fa fa-pencil-square-o fa-lg" ,remote: true %>
            <%= link_to '', topic_comment_path(topic, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
          </p>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/_update.html.erb
<%= render partial: 'index', locals: {topic: @topic , comments: @topic.comments.order(created_at: :asc)} %>
<%= render partial: 'form', locals: { comment: @topic.comments.build , topic: @topic } %>

app/views/comments/edit.js.erb
$("#comments_input_area").html("<%= j(render 'comments/edit', { comments: @comment.topic.comments, topic: @comment.topic }) %>")

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.topic.comments, topic: @comment.topic }) %>")
$(':text').val('')

app/views/comments/update.js.erb
$("#comments_input_area").html("<%= j(render 'comments/update', { comments: @comment.topic.comments, topic: @comment.topic }) %>")
$(':text').val('')