config/routes.rb
Rails.application.routes.draw do

  get 'notification/index'
  get 'relationships/create'
  get 'relationships/destroy'
  get 'topics/my_topic' => 'topics#my_topic'
  resources :users, only: [:index]
  resources :relationships, only:[:create, :destroy]
  resources :conversations do
    resources :messages
  end

  devise_for :users, controllers:{
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :topics do
    resources :comments
    resources :likes, only:[:create, :destroy]

    collection do
      post :confirmed
    end
  end

  root 'topics#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine,at: "/letter_opener"
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  validates :content, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def like_topic(user_id)
    likes.find_by(user_id: user_id)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.page(params[:page]).order(created_at: :desc)
    @topic = Topic.new
    @likes = Like.limit(10).order(created_at: :desc)
  end

  def my_topic
    @topic = Topic.new
    @topics = Topic.where(user_id: current_user.id).order(created_at: :desc)
    @users = User.all
    @likes = Like.limit(10)

  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @comment = @topic.comments.build
    @comments = @topic.comments.order(created_at: :asc)
    Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: '記事を投稿しました。' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topics_path, notice: '記事を更新しました。' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: '記事を削除しました。' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_topic
    @topic = Topic.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def topic_params
    params.require(:topic).permit(:title, :content, :image, :image_cache)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
    <%= form_for(@topic) do |f| %>
    <% if @topic.errors.any? %>
    <div id="error_explanation">
      <ul>
        エラー:<% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="panel">
      <div class="panel-heading">
        <div class="field">
          <%= f.text_area :content , :placeholder => "今なにしてる？" ,class: 'form-control'%>
        </div>
      </div>
      <div class="panel-body">
        <div class="field">
          <% if @topic.image? %>
          <div class="thumbnail">
            <%= image_tag @topic.image.url %>
          </div>
          <% end %><br>
          <%= f.file_field :image %>
          <%= f.hidden_field :image_cache %>
        </div>
        <div class="actions">
          <%= f.submit "投稿する", class: 'btn btn-primary btn-sm' %>
        </div>
        <% end %>
      </div>
    </div>

app/views/topics/_friends_index.html.erb
<div class="panel">
  <div class="panel-heading">
    フォローされているユーザー(
    <%=current_user.followers.count%>人)
  </div>
  <div class="panel-body">
    <% current_user.followers.order("RANDOM()").first(5).each do |f| %>
    <%= profile_img(f)%>
    <p><%= f.name%></p>
    <% end %>
  </div>
</div>

<div class="panel">
  <div class="panel-heading">
    フォローしているユーザー(<%=current_user.followed_users.count%>人)
  </div>
  <div class="panel-body">
    <% current_user.followed_users.order("RANDOM()").first(5).each do |f| %>
    <%= profile_img(f)%>
    <p><%= f.name%></p>
    <% end %>
  </div>
</div>

app/views/topics/_like_form.html.erb
<span id="like_area_<%= topic.id%>">
  <% unless topic.like_topic(current_user) %>
  <%= link_to 'いいね！する', topic_likes_path(topic) ,class:"fa fa-thumbs-o-up",  method: :post,remote: true %>
  <% else %>
  <%= link_to 'いいね！を取り消す', topic_like_path(topic,user_id: current_user.id,topic_id: topic.id) ,class:"fa fa-thumbs-up", method: :delete, remote: true %>
  <% end %>
</span>

app/views/topics/_like_index.html.erb
<div class="panel">
  <div class="panel-heading">
    <% @likes.each do |like| %>
    <p><%= profile_img(like.user) %><%= like.user.name %>が
      <%if like.user.name == like.topic.user.name %>
      自分
      <% else %>
      <%= like.topic.user.name %>
      <% end %>
      の<%= link_to "投稿",topic_path(like.topic.id)%> にいいね！しました。</p>
      <% end %>
    </div>
  </div>

app/views/topics/edit.html.erb
<h2>投稿を編集する</h2>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
    <p id="notice"><%= notice %></p>
    <%= render 'form' %>
  </div>
  <div class="col-md-8 col-md-offset-0 col-sm-8 col-sm-offset-2">
    <% @topics.each do |topic| %>
    <div class="panel">
      <div class="panel-heading">
        <%=image_tag topic.user.image_url %><%= topic.user.name %>さんが投稿しました。
        <% if current_user.id == topic.user.id %>
        <div class="btn-group btn-group-xs">
          <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to '投稿を編集する', edit_topic_path(topic) %></li>
            <li><%= link_to '投稿を削除する', topic, method: :delete, data: { confirm: '投稿を削除しますか？' } %></li>
          </ul>
        </div>
        <% end %>
      </div>
      <div class="panel-body">
        <p><%= topic.content %></p>
        <% if topic.image.url %>
        <div class="thumbnail">
          <%= image_tag topic.image.url %>
        </div>
        <% end %>
        <%= link_to 'コメントする　', topic, class:"fa fa-comment-o" %>
        <%= render 'like_form', user: current_user, topic: topic %>
        <%= paginate @topics %>
      </div>
    </div>
    <% end %>
  </div>
  <% if @likes.present? %>
  <div class="col-md-4 hidden-sm hidden-xs">
    <%= render "like_index"%>
  </div>
  <% end %>
</div>

app/views/topics/my_topic.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="col-md-3 col-md-offset-1 ">
    <div class="panel">
      <div class="profile">
        <%= profile_img(current_user)%>
        <p><%= current_user.name%></p>
      </div>
    </div>
  </div>
  <div class="col-md-7 ">
    <%= render 'form' %>
  </div>
</div>
<div class="container">
  <div class="col-md-3 col-md-offset-1 hidden-sm hidden-xs">
    <%= render "friends_index"%>
  </div>
  <div class="col-md-7">
    <% @topics.each do |topic| %>
    <div class="panel">
      <div class="panel-heading">
        <%=image_tag topic.user.image_url %><%= topic.user.name %>さんが投稿しました。
        <div class="btn-group btn-group-xs">
          <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to '投稿を編集する', edit_topic_path(topic) %></li>
            <li><%= link_to '投稿を削除する', topic, method: :delete, data: { confirm: '投稿を削除しますか？' } %></li>
          </ul>
        </div>
        <p><%= topic.content %></p>
        <div class="thumbnail">
          <%= image_tag topic.image.url %>
        </div>
        <%= link_to 'コメントする　', topic, class:"fa fa-comment-o" %>
        <%= render 'like_form', user: current_user, topic: topic %>
      </div>
    </div>
    <% end %>
  </div>
</div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
    <p id="notice"><%= notice %></p>
    <div class="child row">
      <div class="topic-text">
        <p class="left"><strong>内容</strong></p>
        <p class="left"><%= @topic.content %></p>
        <% if @topic.image.url %>
        <div class="thumbnail">
          <%= image_tag @topic.image.url %>
        </div>
        <% end %>
        <p class="right">
          <strong>作成時間:</strong>
          <%= @topic.created_at.strftime("%y/%m/%d %p %l:%M") %>
        </p>
        <%= render 'like_form', user: current_user, topic: @topic %>
      </div>
      <p>コメント一覧</p>
      <div id="comments_input_area">
        <div id="comments_area">
          <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
        </div>
        <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
        <% if current_user.id == @topic.user_id %>
        <%= link_to '編集', edit_topic_path(@topic) %> |
        <% end %>
        <%= link_to '戻る', topics_path %>
      </div>
    </div>
  </div>
</div>