config/routes.rb
Rails.application.routes.draw do

  get 'notification/index'
  get 'relationships/create'
  get 'relationships/destroy'
  get 'topics/my_topic' => 'topics#my_topic'
  resources :users, only: [:index]
  resources :relationships, only:[:create, :destroy]
  resources :conversations do
    resources :messages
  end

  devise_for :users, controllers:{
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :topics do
    resources :comments
    resources :likes, only:[:create, :destroy]

    collection do
      post :confirmed
    end
  end

  root 'topics#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine,at: "/letter_opener"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many :notifications, dependent: :destroy
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, scope: :recipient_id
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND  conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end

  def target_user(current_user)
    if sender_id == current_user.id
      User.find(recipient_id)
    elsif recipient_id == current_user.id
      User.find(sender_id)
    end
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation, :user_id
  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  validates :content, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def like_topic(user_id)
    likes.find_by(user_id: user_id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable ,:confirmable, :omniauthable
  has_many :topics, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :followers,through: :reverse_relationships, source: :follower
  has_many :reverse_relationships, foreign_key:"followed_id" ,class_name:"Relationship", dependent: :destroy
  mount_uploader :avatar, AvatarUploader

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end
  def self.create_unique_string
    SecureRandom.uuid
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)

  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  respond_to :js
  def create
    @like = current_user.likes.create!(user_id: current_user.id, topic_id: params[:topic_id],likes_count: 1)
    @topic = Topic.find_by(id: params[:topic_id])
    @topics = Topic.all
    @likes = Like.where(topic_id: params[:topic_id])

  end

  def destroy
    like = Like.find_by(user_id: current_user.id, topic_id: params[:topic_id])
    @topic = Topic.find_by(id: params[:topic_id])
    like.destroy
  end

  private
  def like_params
    params.require(:like).permit(:user_id,:topic_id)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.page(params[:page]).order(created_at: :desc)
    @topic = Topic.new
    @likes = Like.limit(10).order(created_at: :desc)
  end

  def my_topic
    @topic = Topic.new
    @topics = Topic.where(user_id: current_user.id).order(created_at: :desc)
    @users = User.all
    @likes = Like.limit(10)

  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @comment = @topic.comments.build
    @comments = @topic.comments.order(created_at: :asc)
    Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: '記事を投稿しました。' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topics_path, notice: '記事を更新しました。' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: '記事を削除しました。' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_topic
    @topic = Topic.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def topic_params
    params.require(:topic).permit(:title, :content, :image, :image_cache)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where.not(id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_img(user)
    return image_tag(user.avatar, alt: user.name ,size: "100×100") if user.avatar?
    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'no_image.png'
    end
    image_tag(img_url, alt: user.name, size: "100×100")
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notification_helper.rb
module NotificationHelper
  def posted_time(time)
    time > Date.today ? "#{time_ago_in_words(time)}" : time.strftime('%m月%d日')
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
  <script src="https://js.pusher.com/3.2/pusher.min.js"></script>
  <title>Facebooklike</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body>
  <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <img><%= link_to image_tag("fb-logo.png"),root_path %></img>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
           <li><%= link_to "#{@notifications_count}",notification_index_path ,class:"fa fa-bell fa-1x"%><span id="unread_count"></span></li>
            <script>
            var pusher = new Pusher('<%= ENV["PUSHER_KEY"] %>',{
              encrypted: true
            });
            var channel = pusher.subscribe('user_<%= current_user.id %>_channel');
            channel.bind('comment_created', function(data) {
              alert(data.message);
            });
            channel.bind('notification_created', function(data) {
              $('#unread_count').html(data.unread_counts);
            });
            </script>
            <li><%= link_to '', topics_my_topic_path , class:"fa fa-address-card"%></li>
            <li><%= link_to '', users_path , class:"fa fa-users" %></li>
            <li><%= link_to '', conversations_path, class:"fa fa-envelope-o" %></li>
            <li><%= link_to '', edit_user_registration_path , class:"fa fa-cog"%></li>
            <li><%= link_to '', destroy_user_session_path,class:"fa fa-sign-out", method: :delete %></li>
            <% else %>
            <li><%= link_to '', new_user_session_path,class:"fa fa-sign-in"  %></li>

            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </header>

  <%= yield %>

</body>
</html>